#pip install --upgrade google-cloud-aiplatform vertexai

import vertexai
from vertexai.preview.vision_models import ImageGenerationModel
model = ImageGenerationModel.from_pretrained("imagen-3.0-generate-001")

prompt_text = "create image of an apple"

response = model.generate_images(
    prompt=prompt_text,
    number_of_images=1
)

generated_images = response.images

if generated_images and len(generated_images) > 0:
    # The 'generated_images' list contains the generated Image object(s).
    # The raw image bytes are typically stored in the '_image_bytes' attribute
    # of the GeneratedImage object.
    image_data = generated_images[0]._image_bytes

    # Define the filename to save the image
    file_name = "generated_apple_vertexai_image.png"

    # Save the image locally
    # No need for base64.b64decode if _image_bytes is already raw bytes
    with open(file_name, "wb") as f:
        f.write(image_data)
    print(f"Image successfully generated and saved as '{file_name}'")
else:
    print("Error: No images were generated by the model.")